try {
  throw new Error();
} catch (e) {}